AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.2
  Exclude:
    - 'frontend/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'node_modules/**/*'
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: compact
Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals
Style/FormatString:
  Enabled: true
  EnforcedStyle: percent
Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading
  SupportedStyles:
    - leading
    - trailing
