inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'frontend/**/*'
    - 'vendor/**/*'
Style/DoubleNegation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: compact
Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals
Style/FormatString:
  Enabled: true
  EnforcedStyle: percent
Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading
  SupportedStyles:
    - leading
    - trailing
Metrics/LineLength:
  Enabled: false # TODO: Remove this after all linelength offenses are worked out
  Max: 80
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/ClassLength:
  Enabled: true # Enable explicitely in test files if wanted
  Exclude:
    - '**/*test.rb'
