---
postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DEV_DATABASE_HOST"] || "localhost" %>
  port: 5432
  username: exercism
  password: apples

test:
  <<: *postgres
  database: exercism_test

development:
  <<: *postgres
  database: exercism_development

production:
  url: <%= ENV["DATABASE_URL"] %>
