name: First Time Issues

on:
  issues:
    types: [opened]

jobs:
  first-time-greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Check if it's a new contributor
        # Based on https://github.com/actions/github-script#welcome-a-first-time-contributor
        id: new-contributor
        uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9 # 3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const creator = context.payload.sender.login
            const opts = github.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'all'
            })
            const issues = await github.paginate(opts)

            return issues.length === 1

      - name: Post friendly comment
        if: steps.new-contributor.outputs.result == 'true'
        uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9 # 3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Hi and welcome to Exercism! 👋\n\nWe have a [community forum](https://forum.exercism.org/) which is the correct place to most the majority of requests:\n- Get help in [Exercism Support](https://forum.exercism.org/c/support/8).\n- Report bugs or suggest improvements in [Bugs & Feature Requests](https://forum.exercism.org/c/exercism/bugs-and-features/126).\n\nIf you are suggesting a new feature or an improvement to Exercism, we also suggest taking a read of [this post](https://github.com/exercism/docs/blob/main/community/good-member/chestertons-fence.md) first.\n\nUnless this issue has been pre-approved (or you are part of the Exercism Team) it will likely be closed without a response. See you in the forum!\n"
            })
